export interface SaeSignGroup {
  sys: string;
  color: string;
  signs: string[];
}

export const SAE_SIGNS: SaeSignGroup[] = [
  { sys:'🫁 Respiratório', color:'#3B7A6E', signs:[
    'Taquipneia (FR > 20)',
    'Bradipneia (FR < 12)',
    'Dispneia',
    'Saturação < 94%',
    'Uso de musculatura acessória',
    'Cianose central ou periférica',
    'Estertores / sibilos',
    'Secreção abundante',
    'Tosse ineficaz',
    'Em ventilação mecânica',
    'Assincronismo ventilatório',
    'Em oxigenoterapia',
  ]},
  { sys:'💔 Cardiovascular', color:'#C0392B', signs:[
    'Hipotensão (PAS < 90)',
    'Hipertensão (PAS > 160)',
    'Taquicardia (FC > 100)',
    'Bradicardia (FC < 60)',
    'PAM < 65 mmHg',
    'Em drogas vasoativas',
    'Arritmia identificada',
    'Perfusão periférica reduzida',
    'Extremidades frias e pálidas',
    'Edema de MMII',
    'Ausculta cardíaca alterada',
    'Pulso fraco / filiforme',
  ]},
  { sys:'🧠 Neurológico', color:'#6B5CA5', signs:[
    'Rebaixamento de consciência',
    'Agitação psicomotora',
    'Delirium (CAM-ICU+)',
    'Glasgow < 13',
    'Pupilas anisocóricas',
    'Déficit motor focal',
    'Afasia / disartria',
    'Confusão mental',
    'Sedado (RASS ≤ -2)',
    'Dor (CPOT ≥ 3)',
    'Convulsão ou pós-ictal',
    'Pescoço rígido / meningismo',
  ]},
  { sys:'🩸 Hemodinâmico/Metabólico', color:'#B5780A', signs:[
    'Lactato elevado (> 2)',
    'Oligúria (< 0,5 ml/kg/h)',
    'Glicemia < 70 mg/dL',
    'Glicemia > 180 mg/dL',
    'Febre (Tax > 37,8°C)',
    'Hipotermia (Tax < 36°C)',
    'Acidose metabólica',
    'Leucocitose (> 12.000)',
    'Leucopenia (< 4.000)',
    'Plaquetopenia (< 100.000)',
    'Creatinina em elevação',
    'Eletrólitos alterados',
  ]},
  { sys:'🩹 Integridade / Tegumentar', color:'#9A6E2E', signs:[
    'LPP presente (qualquer estágio)',
    'Ferida cirúrgica com deiscência',
    'Ferida infectada / ISC',
    'Icterícia',
    'Exantema / rash cutâneo',
    'Edema generalizado (anasarca)',
    'Mucosas secas / ressecadas',
    'Pele úmida / sudorese',
    'Petéquias / equimoses',
    'Curativo com exsudato abundante',
  ]},
  { sys:'🍽 Gastrointestinal / Nutricional', color:'#2E7D55', signs:[
    'Náusea / vômito',
    'Distensão abdominal',
    'Ruídos hidroaéreos ausentes',
    'Diarreia > 3x/dia',
    'Obstipação > 3 dias',
    'TNE em uso',
    'Resíduo gástrico elevado (> 200 ml)',
    'Disfagia / sem deglutição',
    'Desnutrição / caquexia',
    'Catabolismo / NPT em uso',
  ]},
  { sys:'📌 Dispositivos / Acessos', color:'#3B7A6E', signs:[
    'TOT — intubado',
    'TQT — traqueostomizado',
    'CVC em uso',
    'PICC em uso',
    'SNE em uso',
    'SVD em uso',
    'PAI (pressão arterial invasiva)',
    'Dreno torácico',
    'Dreno abdominal',
    'Diálise / TRRC',
    'Marca-passo provisório',
    'Balão intra-aórtico',
  ]},
];

export const SAE_SETORES = ['UTI Adulto','Pronto-Socorro','Clínica Médica','Clínica Cirúrgica','Oncologia','Neurocirurgia'];
